from __future__ import annotations

import os

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+psycopg://araipet:araipet@localhost:5432/araipet")
WS_HOST = os.getenv("WS_HOST", "0.0.0.0")
WS_PORT = int(os.getenv("WS_PORT", "8080"))
MCP_HOST = os.getenv("MCP_HOST", "0.0.0.0")
MCP_PORT = int(os.getenv("MCP_PORT", "8081"))
DATA_SERVICE_WS_URL = os.getenv("DATA_SERVICE_WS_URL", "ws://localhost:8080/ws")
DATA_SERVICE_TIMEOUT_SECONDS = float(os.getenv("DATA_SERVICE_TIMEOUT_SECONDS", "5"))
MCP_URL = os.getenv("MCP_URL", "http://localhost:8081/mcp")
AGENT_HOST = os.getenv("AGENT_HOST", "0.0.0.0")
AGENT_PORT = int(os.getenv("AGENT_PORT", "8082"))
AGENT_PROVIDER = os.getenv("AGENT_PROVIDER", "openai")
AGENT_LLM_BASE_URL = os.getenv("AGENT_LLM_BASE_URL", "https://api.openai.com/v1")
AGENT_LLM_API_KEY = os.getenv("AGENT_LLM_API_KEY", "")
AGENT_LLM_MODEL = os.getenv("AGENT_LLM_MODEL", "gpt-4o-mini")
AGENT_LLM_TIMEOUT_SECONDS = float(os.getenv("AGENT_LLM_TIMEOUT_SECONDS", "30"))
AGENT_MAX_TOOL_ROUNDS = int(os.getenv("AGENT_MAX_TOOL_ROUNDS", "3"))
AGENT_TIMEZONE = os.getenv("AGENT_TIMEZONE", "Asia/Shanghai")
MEMORY_HOST = os.getenv("MEMORY_HOST", "0.0.0.0")
MEMORY_PORT = int(os.getenv("MEMORY_PORT", "8083"))
MEMORY_WS_URL = os.getenv("MEMORY_WS_URL", "ws://localhost:8083/ws")
MEMORY_PROVIDER = os.getenv("MEMORY_PROVIDER", "mock")
MEMORY_WORKER_INTERVAL_SECONDS = float(os.getenv("MEMORY_WORKER_INTERVAL_SECONDS", "2"))
MEMORY_MAX_ATTEMPTS = int(os.getenv("MEMORY_MAX_ATTEMPTS", "3"))
MEMORY_JOB_LEASE_SECONDS = int(os.getenv("MEMORY_JOB_LEASE_SECONDS", "60"))
MEMORY_RETRY_BASE_SECONDS = int(os.getenv("MEMORY_RETRY_BASE_SECONDS", "5"))
MEMORY_SEARCH_TIMEOUT_SECONDS = float(os.getenv("MEMORY_SEARCH_TIMEOUT_SECONDS", "2"))
MEM0_ENABLED = os.getenv("MEM0_ENABLED", "false").lower() in {"1", "true", "yes", "on"}
MEM0_QDRANT_URL = os.getenv("MEM0_QDRANT_URL", "http://localhost:6333")
MEM0_COLLECTION = os.getenv("MEM0_COLLECTION", "araipet_memories")
MEM0_HISTORY_DB_PATH = os.getenv("MEM0_HISTORY_DB_PATH", "/data/mem0-history.db")
MEM0_LLM_PROVIDER = os.getenv("MEM0_LLM_PROVIDER", "openai")
MEM0_LLM_BASE_URL = os.getenv("MEM0_LLM_BASE_URL", "https://api.openai.com/v1")
MEM0_LLM_API_KEY = os.getenv("MEM0_LLM_API_KEY", "")
MEM0_LLM_MODEL = os.getenv("MEM0_LLM_MODEL", "gpt-4o-mini")
MEM0_EMBEDDER_PROVIDER = os.getenv("MEM0_EMBEDDER_PROVIDER", "openai")
MEM0_EMBEDDER_BASE_URL = os.getenv("MEM0_EMBEDDER_BASE_URL", "https://api.openai.com/v1")
MEM0_EMBEDDER_API_KEY = os.getenv("MEM0_EMBEDDER_API_KEY", "")
MEM0_EMBEDDER_MODEL = os.getenv("MEM0_EMBEDDER_MODEL", "text-embedding-3-small")
MEM0_EMBEDDING_DIMS = int(os.getenv("MEM0_EMBEDDING_DIMS", "1536"))
MEMORY_MOCK_PATH = os.getenv("MEMORY_MOCK_PATH", "/data/mock_memories.json")
PERSONA_ROOT = os.getenv("PERSONA_ROOT", "/app/content/runtime")
EXPERIENCE_TICK_SECONDS = float(os.getenv("EXPERIENCE_TICK_SECONDS", "5"))
FARM_TICK_SECONDS = int(os.getenv("FARM_TICK_SECONDS", "30"))
PROTOCOL_VERSION = "0.1"
